import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'src/rust/api/simple.dart'; // Generated by the bridge

void main() => runApp(const VelocityApp());

class VelocityApp extends StatelessWidget {
  const VelocityApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.dark, primaryColor: Colors.teal),
      home: const MainDashboard(),
    );
  }
}

class MainDashboard extends StatefulWidget {
  const MainDashboard({super.key});
  @override
  State<MainDashboard> createState() => _MainDashboardState();
}

class _MainDashboardState extends State<MainDashboard> {
  String balance = "0.00";

  @override
  void initState() {
    super.initState();
    _refreshBalance();
  }

  // Calls the Rust Engine
  Future<void> _refreshBalance() async {
    final result = await calculateBalance(ledger: "Cash in Hand");
    setState(() => balance = result.amount);
  }

  @override
  Widget build(BuildContext context) {
    return Shortcuts(
      shortcuts: <LogicalKeySet, Intent>{
        LogicalKeySet(LogicalKeyboardKey.alt, LogicalKeyboardKey.keyG): const GoToIntent(),
      },
      child: Actions(
        actions: <Type, Action<Intent>>{
          GoToIntent: CallbackAction<GoToIntent>(onInvoke: (intent) => _showGoToSearch(context)),
        },
        child: Scaffold(
          appBar: AppBar(title: const Text("Velocity-ERP | Dashboard")),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text("Ledger: Cash in Hand", style: TextStyle(fontSize: 20)),
                Text("₹ $balance", style: const TextStyle(fontSize: 48, fontWeight: FontWeight.bold, color: Colors.greenAccent)),
                const SizedBox(height: 20),
                const Text("Press [Alt + G] to search like Tally", style: TextStyle(color: Colors.grey)),
              ],
            ),
          ),
        ),
      ),
    );
  }

  void _showGoToSearch(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) => const SearchPalette(),
    );
  }
}

class GoToIntent extends Intent { const GoToIntent(); }